# Generated by Django 5.1 on 2024-09-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id_vuln', models.AutoField(primary_key=True, serialize=False)),
                ('vulnerability', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('implemented_security_measures', models.TextField()),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('cwe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_content', models.TextField()),
                ('id_vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='demo.vuln')),
            ],
        ),
    ]
