# Generated by Django 5.1 on 2024-09-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id_file',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='id_vuln',
            new_name='vuln',
        ),
        migrations.RenameField(
            model_name='vuln',
            old_name='id_vuln',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cwe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='priority',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='risk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
