# Generated by Django 5.1 on 2024-10-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
